---
title: "Determinantes de la participación electoral en México"
author: "Rodrigo Franco Fuentes"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output: 
  pdf_document:
  number_sections: yes
  toc: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "Figuras/", warning = FALSE,
                      message =FALSE, cache = TRUE, fig.width =12, 
                      fig.height = 8)

library(knitr)
library(rgeos)
library(rgdal)
library(raster)
library(ggplot2)
library(dplyr)
library(gtable)
library(grid)
library(stringr)
library(data.table)
library(viridis)
library(tidyr)
library(kableExtra)
library(gridExtra)
library(lattice)
library(PerformanceAnalytics)#para correlaciones del voto 
library(broom) #tidy en vez de fortify
library(foreign )

# Función para referencia de entradas 
fig <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Figure ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

theme_map <- function(...) {
  theme_minimal() +
    theme(
      text = element_text(family = "sans", color = "#22211d"),
      axis.line = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      # panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
      panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = "#f5f5f2", color = NA), 
      panel.background = element_rect(fill = "#f5f5f2", color = NA), 
      legend.background = element_rect(fill = "#f5f5f2", color = NA),
      panel.border = element_blank()
      )
}
``` 

\renewcommand{\contentsname}{Índice}
\tableofcontents


```{r Cap-1, child = 'Capitulos/Cap_1.Rmd', cache = TRUE}
```
```{r Cap-2, child = 'Capitulos/Cap_2.Rmd', cache = TRUE}
```
```{r Cap-3, child = 'Capitulos/Cap_3.Rmd', cache = TRUE}
```
```{r Cap-4, child = 'Capitulos/Cap_4.Rmd', cache = TRUE}
```
```{r Cap-5, child = 'Capitulos/Cap_5.Rmd', cache = TRUE}
```
```{r Cap-6, child = 'Capitulos/Cap_6.Rmd', cache = TRUE}
```


\begin{appendix}
  \listoffigures
  \listoftables
\end{appendix}

